name: big_slider
description: A slider that handles multi-touch interactions across the whole surface
version: 0.0.1
author: Romain Laboisse labrom@gmail.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:
